export const ICON_OPTIONS = [
  { value: 'Truck', label: 'Truck (delivery)' },
  { value: 'Package', label: 'Package (box)' },
  { value: 'Boxes', label: 'Boxes (stock)' },
  { value: 'PackageCheck', label: 'Package check (dispatched)' },
  { value: 'ShieldCheck', label: 'Shield check (warranty)' },
  { value: 'BadgeCheck', label: 'Badge check (verified)' },
  { value: 'Award', label: 'Award (quality)' },
  { value: 'Star', label: 'Star (rating)' },
  { value: 'ThumbsUp', label: 'Thumbs up (trusted)' },
  { value: 'Heart', label: 'Heart (loved)' },
  { value: 'Clock', label: 'Clock (24/7)' },
  { value: 'Zap', label: 'Zap (fast)' },
  { value: 'Rocket', label: 'Rocket (quick dispatch)' },
  { value: 'Headphones', label: 'Headphones (support)' },
  { value: 'MessageCircle', label: 'Message (chat support)' },
  { value: 'Phone', label: 'Phone (call us)' },
  { value: 'Users', label: 'Users (account manager)' },
  { value: 'Receipt', label: 'Receipt (GST invoice)' },
  { value: 'FileText', label: 'File text (documents)' },
  { value: 'Wallet', label: 'Wallet (payments)' },
  { value: 'CreditCard', label: 'Credit card (card payment)' },
  { value: 'Banknote', label: 'Banknote (cash on delivery)' },
  { value: 'TrendingDown', label: 'Trending down (bulk discount)' },
  { value: 'Percent', label: 'Percent (savings)' },
  { value: 'Tag', label: 'Tag (pricing)' },
  { value: 'RotateCcw', label: 'Rotate (easy returns)' },
  { value: 'Wrench', label: 'Wrench (tools)' },
  { value: 'Factory', label: 'Factory (industrial)' },
  { value: 'Warehouse', label: 'Warehouse (inventory)' },
  { value: 'MapPin', label: 'Map pin (pan-India)' },
  { value: 'Globe', label: 'Globe (nationwide)' },
  { value: 'Lock', label: 'Lock (secure)' },
]
