import {
  Package,
  FolderTree,
  Boxes,
  Warehouse,
  Sparkles,
  ShoppingCart,
  Store,
  FileSignature,
  TicketPercent,
  Star,
  Truck,
  ScrollText,
  Barcode,
  Undo2,
  FileText,
  CreditCard,
  LineChart,
  Banknote,
  Megaphone,
  Mail,
  Share2,
  BadgePercent,
  Building2,
  Handshake,
  Tags,
  Users,
  LayoutDashboard,
  Bot,
  UserCog,
  Activity,
  LayoutGrid,
  type LucideIcon,
} from 'lucide-react'

const ICONS: Record<string, LucideIcon> = {
  Package,
  FolderTree,
  Boxes,
  Warehouse,
  Sparkles,
  ShoppingCart,
  Store,
  FileSignature,
  TicketPercent,
  Star,
  Truck,
  ScrollText,
  Barcode,
  Undo2,
  FileText,
  CreditCard,
  LineChart,
  Banknote,
  Megaphone,
  Mail,
  Share2,
  BadgePercent,
  Building2,
  Handshake,
  Tags,
  Users,
  LayoutDashboard,
  Bot,
  UserCog,
  Activity,
}

export default function AppIcon({ name, className = '' }: { name: string; className?: string }) {
  const Icon = ICONS[name] ?? LayoutGrid
  return <Icon className={className} aria-hidden />
}
