--
-- Plans and their admin-scope entitlements.
--
-- These four rows are reference data the product cannot run without: listPlans() drives the
-- plan picker on /ecom/onboard, and createTenant() rejects a signup whose slug is not found
-- here ("Unknown or inactive plan"). The control plane was truncated on 2026-08-29 and there
-- was no seed in the repo, so onboarding broke live with an empty picker and that error.
--
-- Re-runnable: plans upsert on their unique slug, features on (plan_id, scope_key), and
-- features are matched to plans by slug so no id is hard-coded.
--
-- Scope keys must stay in step with ADMIN_SCOPES in src/lib/scopes.ts — a key that no longer
-- exists there simply grants nothing.
--

BEGIN;

INSERT INTO public.plans (slug, name, tier, monthly_price_inr, max_custom_domains, is_active) VALUES
  ('basic', 'Basic', 1, 4999.00, 0, true),
  ('growth', 'Growth', 2, 9999.00, 0, true),
  ('pro', 'Pro', 3, 19999.00, 1, true),
  ('enterprise', 'Enterprise', 4, 49999.00, 3, true)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, tier = EXCLUDED.tier,
  monthly_price_inr = EXCLUDED.monthly_price_inr,
  max_custom_domains = EXCLUDED.max_custom_domains,
  is_active = EXCLUDED.is_active, updated_at = now();

INSERT INTO public.plan_features (plan_id, scope_key)
SELECT p.id, v.scope_key
FROM public.plans p
JOIN (VALUES
  ('basic', 'brands:read'),
  ('basic', 'brands:write'),
  ('basic', 'categories:read'),
  ('basic', 'categories:write'),
  ('basic', 'controls:read'),
  ('basic', 'controls:write'),
  ('basic', 'customers:read'),
  ('basic', 'customers:write'),
  ('basic', 'dashboard:read'),
  ('basic', 'notifications:read'),
  ('basic', 'delhivery:read'),
  ('basic', 'delhivery:write'),
  ('basic', 'orders:read'),
  ('basic', 'orders:write'),
  ('basic', 'products:read'),
  ('basic', 'products:write'),
  ('basic', 'quick_scan:read'),
  ('basic', 'quick_scan:write'),
  ('basic', 'reviews:read'),
  ('basic', 'reviews:write'),
  ('basic', 'settings:read'),
  ('basic', 'settings:write'),
  ('basic', 'audit:read'),
  ('growth', 'brands:read'),
  ('growth', 'brands:write'),
  ('growth', 'categories:read'),
  ('growth', 'categories:write'),
  ('growth', 'controls:read'),
  ('growth', 'controls:write'),
  ('growth', 'coupons:read'),
  ('growth', 'coupons:write'),
  ('growth', 'crm:read'),
  ('growth', 'crm:write'),
  ('growth', 'customers:read'),
  ('growth', 'customers:write'),
  ('growth', 'dashboard:read'),
  ('growth', 'notifications:read'),
  ('growth', 'delhivery:read'),
  ('growth', 'delhivery:write'),
  ('growth', 'gst:read'),
  ('growth', 'gst:write'),
  ('growth', 'inventory:read'),
  ('growth', 'inventory:write'),
  ('growth', 'invoices:read'),
  ('growth', 'invoices:write'),
  ('growth', 'labels:read'),
  ('growth', 'labels:write'),
  ('growth', 'orders:read'),
  ('growth', 'orders:write'),
  ('growth', 'packing_slips:read'),
  ('growth', 'packing_slips:write'),
  ('growth', 'products:read'),
  ('growth', 'products:write'),
  ('growth', 'quick_scan:read'),
  ('growth', 'quick_scan:write'),
  ('growth', 'quotations:read'),
  ('growth', 'quotations:write'),
  ('growth', 'replacements:read'),
  ('growth', 'replacements:write'),
  ('growth', 'returns:read'),
  ('growth', 'returns:write'),
  ('growth', 'review_forms:read'),
  ('growth', 'review_forms:write'),
  ('growth', 'reviews:read'),
  ('growth', 'reviews:write'),
  ('growth', 'settings:read'),
  ('growth', 'settings:write'),
  ('growth', 'shelving:read'),
  ('growth', 'shelving:write'),
  ('growth', 'tasks:read'),
  ('growth', 'tasks:write'),
  ('growth', 'traffic:read'),
  ('pro', 'agent:read'),
  ('pro', 'agent:write'),
  ('pro', 'brands:read'),
  ('pro', 'brands:write'),
  ('pro', 'business_customers:read'),
  ('pro', 'business_customers:write'),
  ('pro', 'business_rfqs:read'),
  ('pro', 'business_rfqs:write'),
  ('pro', 'campaigns:read'),
  ('pro', 'campaigns:write'),
  ('pro', 'catalog_enrichment:read'),
  ('pro', 'catalog_enrichment:write'),
  ('pro', 'categories:read'),
  ('pro', 'categories:write'),
  ('pro', 'controls:read'),
  ('pro', 'controls:write'),
  ('pro', 'coupons:read'),
  ('pro', 'coupons:write'),
  ('pro', 'crm:read'),
  ('pro', 'crm:write'),
  ('pro', 'customers:read'),
  ('pro', 'customers:write'),
  ('pro', 'dashboard:read'),
  ('pro', 'notifications:read'),
  ('pro', 'delhivery:read'),
  ('pro', 'delhivery:write'),
  ('pro', 'financial:read'),
  ('pro', 'financial:write'),
  ('pro', 'gst:read'),
  ('pro', 'gst:write'),
  ('pro', 'inflation:read'),
  ('pro', 'inflation:write'),
  ('pro', 'inventory:read'),
  ('pro', 'inventory:write'),
  ('pro', 'invoices:read'),
  ('pro', 'invoices:write'),
  ('pro', 'labels:read'),
  ('pro', 'labels:write'),
  ('pro', 'mailer:read'),
  ('pro', 'mailer:write'),
  ('pro', 'merchant_sync:read'),
  ('pro', 'merchant_sync:write'),
  ('pro', 'orders:read'),
  ('pro', 'orders:write'),
  ('pro', 'packing_slips:read'),
  ('pro', 'packing_slips:write'),
  ('pro', 'products:read'),
  ('pro', 'products:write'),
  ('pro', 'quick_scan:read'),
  ('pro', 'quick_scan:write'),
  ('pro', 'quotations:read'),
  ('pro', 'quotations:write'),
  ('pro', 'replacements:read'),
  ('pro', 'replacements:write'),
  ('pro', 'returns:read'),
  ('pro', 'returns:write'),
  ('pro', 'review_forms:read'),
  ('pro', 'review_forms:write'),
  ('pro', 'reviews:read'),
  ('pro', 'reviews:write'),
  ('pro', 'settings:read'),
  ('pro', 'settings:write'),
  ('pro', 'shelving:read'),
  ('pro', 'shelving:write'),
  ('pro', 'tasks:read'),
  ('pro', 'tasks:write'),
  ('pro', 'traffic:read'),
  ('enterprise', 'agent:read'),
  ('enterprise', 'agent:write'),
  ('enterprise', 'audit:read'),
  ('enterprise', 'audit:write'),
  ('enterprise', 'brands:read'),
  ('enterprise', 'brands:write'),
  ('enterprise', 'business_customers:read'),
  ('enterprise', 'business_customers:write'),
  ('enterprise', 'business_rfqs:read'),
  ('enterprise', 'business_rfqs:write'),
  ('enterprise', 'campaigns:read'),
  ('enterprise', 'campaigns:write'),
  ('enterprise', 'catalog_enrichment:read'),
  ('enterprise', 'catalog_enrichment:write'),
  ('enterprise', 'categories:read'),
  ('enterprise', 'categories:write'),
  ('enterprise', 'controls:read'),
  ('enterprise', 'controls:write'),
  ('enterprise', 'coupons:read'),
  ('enterprise', 'coupons:write'),
  ('enterprise', 'crm:read'),
  ('enterprise', 'crm:write'),
  ('enterprise', 'customers:read'),
  ('enterprise', 'customers:write'),
  ('enterprise', 'dashboard:read'),
  ('enterprise', 'notifications:read'),
  ('enterprise', 'delhivery:read'),
  ('enterprise', 'delhivery:write'),
  ('enterprise', 'financial:read'),
  ('enterprise', 'financial:write'),
  ('enterprise', 'gst:read'),
  ('enterprise', 'gst:write'),
  ('enterprise', 'inflation:read'),
  ('enterprise', 'inflation:write'),
  ('enterprise', 'inventory:read'),
  ('enterprise', 'inventory:write'),
  ('enterprise', 'invoices:read'),
  ('enterprise', 'invoices:write'),
  ('enterprise', 'labels:read'),
  ('enterprise', 'labels:write'),
  ('enterprise', 'mailer:read'),
  ('enterprise', 'mailer:write'),
  ('enterprise', 'merchant_sync:read'),
  ('enterprise', 'merchant_sync:write'),
  ('enterprise', 'orders:read'),
  ('enterprise', 'orders:write'),
  ('enterprise', 'packing_slips:read'),
  ('enterprise', 'packing_slips:write'),
  ('enterprise', 'products:read'),
  ('enterprise', 'products:write'),
  ('enterprise', 'quick_scan:read'),
  ('enterprise', 'quick_scan:write'),
  ('enterprise', 'quotations:read'),
  ('enterprise', 'quotations:write'),
  ('enterprise', 'replacements:read'),
  ('enterprise', 'replacements:write'),
  ('enterprise', 'replication:read'),
  ('enterprise', 'returns:read'),
  ('enterprise', 'returns:write'),
  ('enterprise', 'review_forms:read'),
  ('enterprise', 'review_forms:write'),
  ('enterprise', 'reviews:read'),
  ('enterprise', 'reviews:write'),
  ('enterprise', 'service_accounts:read'),
  ('enterprise', 'service_accounts:write'),
  ('enterprise', 'settings:read'),
  ('enterprise', 'settings:write'),
  ('enterprise', 'shelving:read'),
  ('enterprise', 'shelving:write'),
  ('enterprise', 'tasks:read'),
  ('enterprise', 'tasks:write'),
  ('enterprise', 'traffic:read')
) AS v(plan_slug, scope_key) ON v.plan_slug = p.slug
ON CONFLICT (plan_id, scope_key) DO NOTHING;

-- Authoritative, not merely additive: prune any plan_features row not in the desired set above.
-- Without this an over-grant inserted by an earlier, looser seed (e.g. Basic carrying
-- merchant_sync/crm/tasks/returns/replacements/traffic) survives every re-run, because the
-- upsert only ever ADDS. Deleting the complement makes this file the single source of truth so
-- the nav a plan exposes always matches what the plan sells.
DELETE FROM public.plan_features pf
USING public.plans p
WHERE pf.plan_id = p.id
  AND NOT EXISTS (
    SELECT 1 FROM (VALUES
      ('basic', 'brands:read'),
      ('basic', 'brands:write'),
      ('basic', 'categories:read'),
      ('basic', 'categories:write'),
      ('basic', 'controls:read'),
      ('basic', 'controls:write'),
      ('basic', 'customers:read'),
      ('basic', 'customers:write'),
      ('basic', 'dashboard:read'),
      ('basic', 'notifications:read'),
      ('basic', 'delhivery:read'),
      ('basic', 'delhivery:write'),
      ('basic', 'orders:read'),
      ('basic', 'orders:write'),
      ('basic', 'products:read'),
      ('basic', 'products:write'),
      ('basic', 'quick_scan:read'),
      ('basic', 'quick_scan:write'),
      ('basic', 'reviews:read'),
      ('basic', 'reviews:write'),
      ('basic', 'settings:read'),
      ('basic', 'settings:write'),
      ('basic', 'audit:read'),
      ('growth', 'brands:read'),
      ('growth', 'brands:write'),
      ('growth', 'categories:read'),
      ('growth', 'categories:write'),
      ('growth', 'controls:read'),
      ('growth', 'controls:write'),
      ('growth', 'coupons:read'),
      ('growth', 'coupons:write'),
      ('growth', 'crm:read'),
      ('growth', 'crm:write'),
      ('growth', 'customers:read'),
      ('growth', 'customers:write'),
      ('growth', 'dashboard:read'),
      ('growth', 'notifications:read'),
      ('growth', 'delhivery:read'),
      ('growth', 'delhivery:write'),
      ('growth', 'gst:read'),
      ('growth', 'gst:write'),
      ('growth', 'inventory:read'),
      ('growth', 'inventory:write'),
      ('growth', 'invoices:read'),
      ('growth', 'invoices:write'),
      ('growth', 'labels:read'),
      ('growth', 'labels:write'),
      ('growth', 'orders:read'),
      ('growth', 'orders:write'),
      ('growth', 'packing_slips:read'),
      ('growth', 'packing_slips:write'),
      ('growth', 'products:read'),
      ('growth', 'products:write'),
      ('growth', 'quick_scan:read'),
      ('growth', 'quick_scan:write'),
      ('growth', 'quotations:read'),
      ('growth', 'quotations:write'),
      ('growth', 'replacements:read'),
      ('growth', 'replacements:write'),
      ('growth', 'returns:read'),
      ('growth', 'returns:write'),
      ('growth', 'review_forms:read'),
      ('growth', 'review_forms:write'),
      ('growth', 'reviews:read'),
      ('growth', 'reviews:write'),
      ('growth', 'settings:read'),
      ('growth', 'settings:write'),
      ('growth', 'shelving:read'),
      ('growth', 'shelving:write'),
      ('growth', 'tasks:read'),
      ('growth', 'tasks:write'),
      ('growth', 'traffic:read'),
      ('pro', 'agent:read'),
      ('pro', 'agent:write'),
      ('pro', 'brands:read'),
      ('pro', 'brands:write'),
      ('pro', 'business_customers:read'),
      ('pro', 'business_customers:write'),
      ('pro', 'business_rfqs:read'),
      ('pro', 'business_rfqs:write'),
      ('pro', 'campaigns:read'),
      ('pro', 'campaigns:write'),
      ('pro', 'catalog_enrichment:read'),
      ('pro', 'catalog_enrichment:write'),
      ('pro', 'categories:read'),
      ('pro', 'categories:write'),
      ('pro', 'controls:read'),
      ('pro', 'controls:write'),
      ('pro', 'coupons:read'),
      ('pro', 'coupons:write'),
      ('pro', 'crm:read'),
      ('pro', 'crm:write'),
      ('pro', 'customers:read'),
      ('pro', 'customers:write'),
      ('pro', 'dashboard:read'),
      ('pro', 'notifications:read'),
      ('pro', 'delhivery:read'),
      ('pro', 'delhivery:write'),
      ('pro', 'financial:read'),
      ('pro', 'financial:write'),
      ('pro', 'gst:read'),
      ('pro', 'gst:write'),
      ('pro', 'inflation:read'),
      ('pro', 'inflation:write'),
      ('pro', 'inventory:read'),
      ('pro', 'inventory:write'),
      ('pro', 'invoices:read'),
      ('pro', 'invoices:write'),
      ('pro', 'labels:read'),
      ('pro', 'labels:write'),
      ('pro', 'mailer:read'),
      ('pro', 'mailer:write'),
      ('pro', 'merchant_sync:read'),
      ('pro', 'merchant_sync:write'),
      ('pro', 'orders:read'),
      ('pro', 'orders:write'),
      ('pro', 'packing_slips:read'),
      ('pro', 'packing_slips:write'),
      ('pro', 'products:read'),
      ('pro', 'products:write'),
      ('pro', 'quick_scan:read'),
      ('pro', 'quick_scan:write'),
      ('pro', 'quotations:read'),
      ('pro', 'quotations:write'),
      ('pro', 'replacements:read'),
      ('pro', 'replacements:write'),
      ('pro', 'returns:read'),
      ('pro', 'returns:write'),
      ('pro', 'review_forms:read'),
      ('pro', 'review_forms:write'),
      ('pro', 'reviews:read'),
      ('pro', 'reviews:write'),
      ('pro', 'settings:read'),
      ('pro', 'settings:write'),
      ('pro', 'shelving:read'),
      ('pro', 'shelving:write'),
      ('pro', 'tasks:read'),
      ('pro', 'tasks:write'),
      ('pro', 'traffic:read'),
      ('enterprise', 'agent:read'),
      ('enterprise', 'agent:write'),
      ('enterprise', 'audit:read'),
      ('enterprise', 'audit:write'),
      ('enterprise', 'brands:read'),
      ('enterprise', 'brands:write'),
      ('enterprise', 'business_customers:read'),
      ('enterprise', 'business_customers:write'),
      ('enterprise', 'business_rfqs:read'),
      ('enterprise', 'business_rfqs:write'),
      ('enterprise', 'campaigns:read'),
      ('enterprise', 'campaigns:write'),
      ('enterprise', 'catalog_enrichment:read'),
      ('enterprise', 'catalog_enrichment:write'),
      ('enterprise', 'categories:read'),
      ('enterprise', 'categories:write'),
      ('enterprise', 'controls:read'),
      ('enterprise', 'controls:write'),
      ('enterprise', 'coupons:read'),
      ('enterprise', 'coupons:write'),
      ('enterprise', 'crm:read'),
      ('enterprise', 'crm:write'),
      ('enterprise', 'customers:read'),
      ('enterprise', 'customers:write'),
      ('enterprise', 'dashboard:read'),
      ('enterprise', 'notifications:read'),
      ('enterprise', 'delhivery:read'),
      ('enterprise', 'delhivery:write'),
      ('enterprise', 'financial:read'),
      ('enterprise', 'financial:write'),
      ('enterprise', 'gst:read'),
      ('enterprise', 'gst:write'),
      ('enterprise', 'inflation:read'),
      ('enterprise', 'inflation:write'),
      ('enterprise', 'inventory:read'),
      ('enterprise', 'inventory:write'),
      ('enterprise', 'invoices:read'),
      ('enterprise', 'invoices:write'),
      ('enterprise', 'labels:read'),
      ('enterprise', 'labels:write'),
      ('enterprise', 'mailer:read'),
      ('enterprise', 'mailer:write'),
      ('enterprise', 'merchant_sync:read'),
      ('enterprise', 'merchant_sync:write'),
      ('enterprise', 'orders:read'),
      ('enterprise', 'orders:write'),
      ('enterprise', 'packing_slips:read'),
      ('enterprise', 'packing_slips:write'),
      ('enterprise', 'products:read'),
      ('enterprise', 'products:write'),
      ('enterprise', 'quick_scan:read'),
      ('enterprise', 'quick_scan:write'),
      ('enterprise', 'quotations:read'),
      ('enterprise', 'quotations:write'),
      ('enterprise', 'replacements:read'),
      ('enterprise', 'replacements:write'),
      ('enterprise', 'replication:read'),
      ('enterprise', 'returns:read'),
      ('enterprise', 'returns:write'),
      ('enterprise', 'review_forms:read'),
      ('enterprise', 'review_forms:write'),
      ('enterprise', 'reviews:read'),
      ('enterprise', 'reviews:write'),
      ('enterprise', 'service_accounts:read'),
      ('enterprise', 'service_accounts:write'),
      ('enterprise', 'settings:read'),
      ('enterprise', 'settings:write'),
      ('enterprise', 'shelving:read'),
      ('enterprise', 'shelving:write'),
      ('enterprise', 'tasks:read'),
      ('enterprise', 'tasks:write'),
      ('enterprise', 'traffic:read')
    ) AS d(plan_slug, scope_key)
    WHERE d.plan_slug = p.slug AND d.scope_key = pf.scope_key
  );

-- Platform sentinel tenant (also in schema.sql, which the pipeline only structure-diffs, so its row
-- never reached live). Flagship writes keyed to the NIL uuid (import_jobs, tenant_integration_credentials)
-- FK to tenants(id) and fail without it.
INSERT INTO public.tenants (id, slug, display_name, status)
VALUES ('00000000-0000-0000-0000-000000000000', 'platform', 'Platform (flagship)', 'active')
ON CONFLICT DO NOTHING;

COMMIT;
