ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_url TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_s3_key TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_is_custom BOOLEAN NOT NULL DEFAULT false;
