import { queryMany, queryOne } from '@/lib/db'

function clamp(n: number, min: number, max: number) { return Math.max(min, Math.min(max, n)) }

interface ToolInputSchema {
  type: 'object'
  properties: Record<string, { type: string; description?: string; default?: unknown; minimum?: number; maximum?: number; enum?: string[] }>
  required?: string[]
}

interface ToolDef {
  name: string
  description: string
  inputSchema: ToolInputSchema
  mutating: boolean
  handler: (input: Record<string, unknown>) => Promise<unknown>
}

const COUPON_CODE_RE = /^[A-Z0-9][A-Z0-9-]{2,28}[A-Z0-9]$/

function validateCouponCode(raw: string): string {
  const code = String(raw || '').trim().toUpperCase()
  if (code.length < 4 || code.length > 30) throw new Error('Coupon code must be 4-30 characters')
  if (!COUPON_CODE_RE.test(code)) throw new Error('Coupon code must be uppercase A-Z, 0-9, or dashes (no leading/trailing dash)')
  return code
}

function validateDiscount(type: string, value: number): { type: string; value: number } {
  const t = String(type || '').toLowerCase()
  if (!['percentage', 'fixed'].includes(t)) throw new Error('discountType must be "percentage" or "fixed"')
  if (!Number.isFinite(value) || value <= 0) throw new Error('discountValue must be > 0')
  if (t === 'percentage' && value > 100) throw new Error('Percentage discount cannot exceed 100')
  if (t === 'fixed' && value > 1_000_000) throw new Error('Fixed discount unreasonably large')
  return { type: t, value }
}

export const MARKETING_TOOLS: ToolDef[] = [
  {
    name: 'list_campaigns',
    description: 'List behavioral email campaigns (the campaigns table) with name, kind, enabled flag, and 30-day send count. Use to answer "which campaigns are running?".',
    inputSchema: {
      type: 'object',
      properties: {
        enabledOnly: { type: 'boolean', description: 'If true, only show enabled campaigns.' },
        kind: { type: 'string', description: 'Optional kind substring filter (e.g. "winback").' },
      },
    },
    mutating: false,
    handler: async ({ enabledOnly, kind }) => {
      const where: string[] = []
      const params: unknown[] = []
      if (enabledOnly === true || String(enabledOnly).toLowerCase() === 'true') where.push('c.enabled = TRUE')
      if (kind) { params.push(`%${String(kind)}%`); where.push(`c.kind ILIKE $${params.length}`) }
      const rows = await queryMany(
        `SELECT c.kind, c.name, c.enabled, c.delay_hours, c.discount_percent, c.scenario_kind,
                COALESCE((SELECT COUNT(*)::int FROM email_campaigns_sent ecs
                            WHERE ecs.campaign_kind = c.kind AND ecs.sent_at > NOW() - INTERVAL '30 days'), 0) AS sent_count_30d
         FROM campaigns c
         ${where.length ? 'WHERE ' + where.join(' AND ') : ''}
         ORDER BY c.name`,
        params
      )
      return { campaigns: rows, count: rows.length }
    },
  },
  {
    name: 'get_campaign',
    description: 'Fetch full template detail for a behavioral campaign — subject template, body template, audience filter (scenario + parameters), and 30-day stats.',
    inputSchema: {
      type: 'object',
      properties: { kind: { type: 'string', description: 'Campaign kind slug, e.g. abandoned_cart.' } },
      required: ['kind'],
    },
    mutating: false,
    handler: async ({ kind }) => {
      const k = String(kind || '').trim()
      if (!k) throw new Error('kind is required')
      const row = await queryOne(
        `SELECT c.kind, c.name, c.description, c.enabled, c.delay_hours, c.discount_percent, c.coupon_id::text,
                c.subject_template, c.body_template, c.scenario_kind, c.parameters, c.last_run_at,
                COALESCE((SELECT COUNT(*)::int FROM email_campaigns_sent ecs
                            WHERE ecs.campaign_kind = c.kind AND ecs.sent_at > NOW() - INTERVAL '30 days'), 0) AS sent_count_30d,
                COALESCE((SELECT COUNT(*)::int FROM email_campaigns_sent ecs
                            WHERE ecs.campaign_kind = c.kind AND ecs.opened_at IS NOT NULL
                              AND ecs.sent_at > NOW() - INTERVAL '30 days'), 0) AS opened_30d
         FROM campaigns c WHERE c.kind = $1 LIMIT 1`,
        [k]
      )
      return row || { error: `Campaign not found: ${k}` }
    },
  },
  {
    name: 'list_coupons',
    description: 'List coupons. By default shows only currently-active human coupons (excludes auto-generated per-user codes from winback/offer campaigns). Use autoGeneratedOnly=true to inspect those.',
    inputSchema: {
      type: 'object',
      properties: {
        activeOnly: { type: 'boolean', description: 'Default true — only currently-active coupons.' },
        autoGeneratedOnly: { type: 'boolean', description: 'If true, only show auto-generated user-specific coupons.' },
        limit: { type: 'integer', default: 25, minimum: 1, maximum: 100 },
      },
    },
    mutating: false,
    handler: async ({ activeOnly, autoGeneratedOnly, limit }) => {
      const lim = clamp(typeof limit === 'number' ? limit : 25, 1, 100)
      const isActive = activeOnly === undefined ? true : !!activeOnly
      const auto = !!autoGeneratedOnly
      const where: string[] = []
      if (isActive) where.push(`c.is_active = TRUE AND (c.valid_until IS NULL OR c.valid_until > NOW())`)
      where.push(auto ? `c.auto_generated = TRUE` : `(c.auto_generated IS NOT TRUE)`)
      const rows = await queryMany(
        `SELECT c.id::text, c.code, c.discount_type, c.discount_value::text, c.min_purchase_amount::text,
                c.max_discount_amount::text, c.usage_limit, c.times_used, c.valid_until, c.is_active,
                c.auto_generated, c.description
         FROM coupons c
         WHERE ${where.join(' AND ')}
         ORDER BY c.created_at DESC LIMIT $1`,
        [lim]
      )
      return { coupons: rows, count: rows.length, truncated: rows.length === lim }
    },
  },
  {
    name: 'get_coupon',
    description: 'Fetch full coupon detail by code or id, including times_used and assignment info.',
    inputSchema: {
      type: 'object',
      properties: { codeOrId: { type: 'string', description: 'Coupon code (e.g. WELCOME10) or UUID.' } },
      required: ['codeOrId'],
    },
    mutating: false,
    handler: async ({ codeOrId }) => {
      const q = String(codeOrId || '').trim()
      if (!q) throw new Error('codeOrId is required')
      const isUuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(q)
      const row = await queryOne(
        `SELECT c.id::text, c.code, c.description, c.discount_type, c.discount_value::text,
                c.min_purchase_amount::text, c.max_discount_amount::text, c.usage_limit,
                c.usage_limit_per_user, c.times_used, c.valid_from, c.valid_until, c.is_active,
                c.auto_generated, c.generated_for_user_id::text, c.generated_for_campaign,
                c.created_at,
                u.email AS generated_for_email
         FROM coupons c
         LEFT JOIN users u ON u.id = c.generated_for_user_id
         WHERE ${isUuid ? 'c.id = $1::uuid' : 'c.code = UPPER($1)'} LIMIT 1`,
        [q]
      )
      return row || { error: `Coupon not found: ${q}` }
    },
  },
  {
    name: 'list_mailer_templates',
    description: 'List recent saved mailer broadcast campaigns (the email_campaigns table) — the one-off blasts the admin has drafted in the mailer UI. Useful as templates / send history.',
    inputSchema: {
      type: 'object',
      properties: { limit: { type: 'integer', default: 20, minimum: 1, maximum: 50 } },
    },
    mutating: false,
    handler: async ({ limit }) => {
      const lim = clamp(typeof limit === 'number' ? limit : 20, 1, 50)
      const rows = await queryMany(
        `SELECT id::text, title, template_key, subject, audience_type, recipient_count, status,
                scheduled_at, sent_at, created_at
         FROM email_campaigns ORDER BY created_at DESC LIMIT $1`,
        [lim]
      )
      return { templates: rows, count: rows.length }
    },
  },
  {
    name: 'propose_create_coupon',
    description: 'Propose creating a new coupon code. Admin must approve before insertion. Code must be 4-30 chars, uppercase A-Z, 0-9, dashes only. Throws on duplicate.',
    inputSchema: {
      type: 'object',
      properties: {
        code: { type: 'string', description: 'Coupon code, e.g. SUMMER25.' },
        discountType: { type: 'string', description: 'percentage | fixed' },
        discountValue: { type: 'number', description: 'Percent (1-100) or rupees.' },
        validUntil: { type: 'string', description: 'ISO date/time. Optional. If omitted, no expiry.' },
        minPurchaseAmount: { type: 'number', description: 'Min cart total to use the coupon. Optional.' },
        usageLimit: { type: 'integer', description: 'Total uses across all customers. Optional.' },
        description: { type: 'string', description: 'Internal description. Optional.' },
      },
      required: ['code', 'discountType', 'discountValue'],
    },
    mutating: true,
    handler: async ({ code, discountType, discountValue, validUntil, minPurchaseAmount, usageLimit, description }) => {
      const cleanCode = validateCouponCode(String(code))
      const dv = validateDiscount(String(discountType), Number(discountValue))
      const dup = await queryOne(`SELECT id FROM coupons WHERE code = $1 LIMIT 1`, [cleanCode])
      if (dup) throw new Error(`Coupon code "${cleanCode}" already exists`)

      const validUntilIso = validUntil ? new Date(String(validUntil)).toISOString() : null
      if (validUntil && Number.isNaN(Date.parse(String(validUntil)))) throw new Error('validUntil is not a valid date')
      const minPurch = typeof minPurchaseAmount === 'number' && minPurchaseAmount > 0 ? minPurchaseAmount : null
      const useLimit = typeof usageLimit === 'number' && usageLimit > 0 ? Math.floor(usageLimit) : null
      const desc = description ? String(description).slice(0, 240) : null

      const exampleAmount = dv.type === 'percentage' ? `${dv.value}% off` : `₹${dv.value} off`
      return {
        proposed: true,
        kind: 'create_coupon',
        payload: {
          code: cleanCode, discountType: dv.type, discountValue: dv.value,
          validUntil: validUntilIso, minPurchaseAmount: minPurch, usageLimit: useLimit, description: desc,
        },
        confirmation: `Create coupon ${cleanCode} (${exampleAmount}${validUntilIso ? `, expires ${validUntilIso.slice(0, 10)}` : ''})?`,
        ui_blocks: [
          { type: 'callout', tone: 'info', title: 'New coupon', message: `${cleanCode} — ${exampleAmount}${useLimit ? `, capped at ${useLimit} uses` : ''}.` },
          {
            type: 'kv_pairs',
            pairs: [
              { key: 'Code', value: cleanCode },
              { key: 'Discount', value: exampleAmount },
              { key: 'Min purchase', value: minPurch ? `₹${minPurch}` : '—' },
              { key: 'Total uses', value: useLimit ? String(useLimit) : 'Unlimited' },
              { key: 'Expires', value: validUntilIso ? validUntilIso.slice(0, 10) : 'Never' },
              { key: 'Description', value: desc || '—' },
            ],
          },
          {
            type: 'text',
            value: `Customer enters ${cleanCode} at checkout for ${exampleAmount}${minPurch ? ` (min cart ₹${minPurch})` : ''}.`,
            weight: 'muted',
          },
        ],
      }
    },
  },
  {
    name: 'propose_update_campaign_template',
    description: 'Propose changing the subject and/or body template of a behavioral campaign. Admin must approve. Pass at least one of newSubject / newBody. A warning callout appears if the body change is large (>50% length diff).',
    inputSchema: {
      type: 'object',
      properties: {
        kind: { type: 'string', description: 'Campaign kind, e.g. abandoned_cart.' },
        newSubject: { type: 'string', description: 'New subject template (under 500 chars).' },
        newBody: { type: 'string', description: 'New body HTML template (under 50,000 chars).' },
      },
      required: ['kind'],
    },
    mutating: true,
    handler: async ({ kind, newSubject, newBody }) => {
      const k = String(kind || '').trim()
      if (!k) throw new Error('kind is required')
      const c = await queryOne<{ kind: string; name: string; subject_template: string; body_template: string }>(
        `SELECT kind, name, subject_template, body_template FROM campaigns WHERE kind = $1`, [k]
      )
      if (!c) throw new Error(`Unknown campaign: ${k}`)
      const subj = newSubject !== undefined ? String(newSubject).trim() : null
      const body = newBody !== undefined ? String(newBody) : null
      if (subj === null && body === null) throw new Error('Provide newSubject and/or newBody')
      if (subj !== null && (subj.length === 0 || subj.length > 500)) throw new Error('newSubject must be 1-500 chars')
      if (body !== null && (body.length === 0 || body.length > 50000)) throw new Error('newBody must be 1-50,000 chars')

      const oldLen = c.body_template?.length || 0
      const newLen = body !== null ? body.length : oldLen
      const diffPct = oldLen > 0 ? Math.abs(newLen - oldLen) / oldLen : (body !== null ? 1 : 0)
      const bigChange = body !== null && diffPct > 0.5

      const subjRows: (string | number)[][] = []
      if (subj !== null) {
        subjRows.push(['Old', c.subject_template || '(empty)'])
        subjRows.push(['New', subj])
      }

      const blocks: any[] = [
        { type: 'kv_pairs', pairs: [
          { key: 'Campaign', value: `${c.name} (${c.kind})` },
          { key: 'Subject change', value: subj !== null ? 'yes' : 'no' },
          { key: 'Body change', value: body !== null ? `yes — ${oldLen} → ${newLen} chars (${Math.round(diffPct * 100)}% diff)` : 'no' },
        ]},
      ]
      if (subjRows.length) blocks.push({ type: 'table', headers: ['', 'Subject'], rows: subjRows })
      if (bigChange) blocks.push({
        type: 'callout', tone: 'warn',
        title: 'Large body rewrite',
        message: `Body length changes by ${Math.round(diffPct * 100)}%. Double-check tracking pixels, unsubscribe link, and merge tags before approving.`,
      })

      return {
        proposed: true,
        kind: 'update_campaign_template',
        payload: { campaignKind: c.kind, campaignName: c.name, newSubject: subj, newBody: body },
        confirmation: `Update ${c.name} template${subj !== null ? ' subject' : ''}${subj !== null && body !== null ? ' and' : ''}${body !== null ? ' body' : ''}?`,
        ui_blocks: blocks,
      }
    },
  },
  {
    name: 'propose_send_mailer_broadcast',
    description: 'Propose a one-off broadcast email (custom subject + HTML body) to a chosen audience. Admin must approve before fan-out. Audience: "all_opted_in", "recent_buyers", or "test_only". When audience=test_only, also pass testEmail.',
    inputSchema: {
      type: 'object',
      properties: {
        audience: { type: 'string', description: 'all_opted_in | recent_buyers | test_only' },
        testEmail: { type: 'string', description: 'Required when audience=test_only. The address to send to.' },
        subject: { type: 'string', description: 'Email subject (1-160 chars).' },
        body: { type: 'string', description: 'HTML body of the email (1-50,000 chars).' },
        fromName: { type: 'string', description: 'Optional display name for the From header. Defaults to the store name.' },
      },
      required: ['audience', 'subject', 'body'],
    },
    mutating: true,
    handler: async ({ audience, testEmail: testEmailArg, subject, body, fromName }) => {
      const subj = String(subject || '').trim()
      const html = String(body || '')
      if (!subj || subj.length > 160) throw new Error('subject required (1-160 chars)')
      if (!html || html.length > 50000) throw new Error('body required (1-50,000 chars)')
      const aRaw = String(audience || '').trim().toLowerCase()
      let audKey: 'all_opted_in' | 'recent_buyers' | 'test_only' = 'all_opted_in'
      let testEmail: string | null = null
      // Accept both "test_only" + testEmail field AND legacy "test_only:email@.." colon format
      if (aRaw.startsWith('test_only:')) {
        audKey = 'test_only'
        testEmail = aRaw.slice('test_only:'.length).trim()
        if (!testEmail.includes('@')) throw new Error('test_only audience needs a valid email after the colon')
      } else if (aRaw === 'test_only') {
        audKey = 'test_only'
        testEmail = String(testEmailArg || '').trim()
        if (!testEmail.includes('@')) throw new Error('testEmail is required when audience=test_only')
      } else if (aRaw === 'all_opted_in' || aRaw === 'recent_buyers') {
        audKey = aRaw
      } else {
        throw new Error('audience must be all_opted_in, recent_buyers, or test_only')
      }

      let count = 0
      if (audKey === 'test_only') count = 1
      else if (audKey === 'all_opted_in') {
        const r = await queryOne<{ n: number }>(
          `SELECT COUNT(*)::int AS n FROM users WHERE email IS NOT NULL AND marketing_opt_out IS NOT TRUE`
        )
        count = r?.n || 0
      } else {
        const r = await queryOne<{ n: number }>(
          `SELECT COUNT(DISTINCT u.id)::int AS n FROM users u JOIN orders o ON o.user_id = u.id
           WHERE u.email IS NOT NULL AND u.marketing_opt_out IS NOT TRUE
             AND o.created_at > NOW() - INTERVAL '90 days'`
        )
        count = r?.n || 0
      }

      const { currentBrandNameAsync } = await import('@/lib/brand')
      const fromN = String(fromName || '').trim().slice(0, 80) || await currentBrandNameAsync()
      const preview = html.slice(0, 500)
      return {
        proposed: true,
        kind: 'send_mailer_broadcast',
        payload: { audience: audKey, testEmail, subject: subj, body: html, fromName: fromN, audienceCount: count },
        confirmation: `Send broadcast "${subj}" to ${count} recipient${count === 1 ? '' : 's'} (${audKey === 'test_only' ? testEmail : audKey})?`,
        ui_blocks: [
          {
            type: 'kv_pairs',
            pairs: [
              { key: 'Subject', value: subj },
              { key: 'From', value: fromN },
              { key: 'Audience', value: audKey === 'test_only' ? `test_only → ${testEmail}` : audKey },
              { key: 'Recipients', value: String(count) },
              { key: 'Body length', value: `${html.length} chars` },
            ],
          },
          { type: 'code_block', language: 'html', content: preview + (html.length > 500 ? '\n... (truncated)' : '') },
        ],
      }
    },
  },
  {
    name: 'propose_generate_personalized_coupon',
    description: 'Propose generating an auto-generated, single-customer coupon (with auto_generated=true and generated_for_user_id set). Admin must approve. Use when the user says "give customer X a 15% off code valid 7 days".',
    inputSchema: {
      type: 'object',
      properties: {
        userId: { type: 'string', description: 'Customer UUID.' },
        discountType: { type: 'string', description: 'percentage | fixed' },
        discountValue: { type: 'number', description: 'Percent (1-100) or rupees.' },
        daysValid: { type: 'integer', default: 30, minimum: 1, maximum: 365 },
        campaign: { type: 'string', description: 'Optional campaign tag, e.g. "manual_offer" or "winback_90".' },
      },
      required: ['userId', 'discountType', 'discountValue'],
    },
    mutating: true,
    handler: async ({ userId, discountType, discountValue, daysValid, campaign }) => {
      const uid = String(userId || '').trim()
      if (!uid) throw new Error('userId is required')
      const dv = validateDiscount(String(discountType), Number(discountValue))
      const days = clamp(typeof daysValid === 'number' ? Math.floor(daysValid) : 30, 1, 365)
      const camp = String(campaign || 'manual_offer').trim().toLowerCase().replace(/[^a-z0-9_]/g, '_').slice(0, 60) || 'manual_offer'

      const u = await queryOne<{ id: string; email: string | null; first_name: string | null; last_name: string | null; marketing_opt_out: boolean }>(
        `SELECT id::text, email, first_name, last_name, marketing_opt_out FROM users WHERE id = $1::uuid LIMIT 1`,
        [uid]
      )
      if (!u) throw new Error(`Customer not found: ${uid}`)
      if (!u.email) throw new Error('Customer has no email — cannot send a personalized coupon')

      const validUntil = new Date(Date.now() + days * 86400000)
      const example = dv.type === 'percentage' ? `${dv.value}% off` : `₹${dv.value} off`
      const customerName = `${u.first_name || ''} ${u.last_name || ''}`.trim() || u.email

      return {
        proposed: true,
        kind: 'generate_personalized_coupon',
        payload: {
          userId: u.id, customerEmail: u.email, customerName,
          discountType: dv.type, discountValue: dv.value, daysValid: days,
          campaign: camp, validUntil: validUntil.toISOString(),
        },
        confirmation: `Generate a ${example} coupon for ${customerName} valid ${days} days (campaign: ${camp})?`,
        ui_blocks: [
          { type: 'callout', tone: u.marketing_opt_out ? 'warn' : 'info',
            title: u.marketing_opt_out ? 'Customer is opted out of marketing' : 'Personalized coupon',
            message: u.marketing_opt_out
              ? 'Coupon will be created but you may not be able to email it via marketing channels — share manually.'
              : `One-time code, single user, ${example}, expires in ${days} days.` },
          {
            type: 'kv_pairs',
            pairs: [
              { key: 'Customer', value: customerName },
              { key: 'Email', value: u.email },
              { key: 'Discount', value: example },
              { key: 'Valid for', value: `${days} day${days === 1 ? '' : 's'} (until ${validUntil.toISOString().slice(0, 10)})` },
              { key: 'Campaign tag', value: camp },
            ],
          },
        ],
      }
    },
  },
]
